version: '3.7'

services:
  terraform:
    command: bash
    volumes:
      - ./:/go/src/github.com/comtravo/terraform-aws-ssm-parameter-store

  localstack:
    ports:
      - 4566:4566
      - 8080:8080
