version: '3.7'

services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    image: terraform-aws-ssm-parameter-store:${GIT_COMMIT:-latest}
    environment:
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-foo}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-foo}
