version: '3.7'

services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    image: terraform-aws-ssm-parameter-store:${GIT_COMMIT:-latest}
    environment:
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - LOCALSTACK_HOST=localstack
    depends_on:
      - start_dependencies

  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
      - 8080:8080
    environment:
      - SERVICES=iam,sts,ssm
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack-data:/tmp/localstack"

  start_dependencies:
    image: puneethn/wait-for-dependencies
    depends_on:
      - localstack
    command: localstack:4566

volumes:
  localstack-data:
